version: '3'  # Versión del archivo docker-compose

services:     # Clave principal que agrupa los servicios
  web:        
    image: web
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "81:80"     # Puerto HTTP
      - "444:443"   # Puerto HTTPS
    links:
      - db
    volumes:
      - ./app:/var/www/html/

  db:         # Servicio de base de datos MariaDB
    image: mariadb:10.8.2
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    ports:
      - "8889:3306"

  phpmyadmin: # Servicio phpMyAdmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "8890:80"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
